# Generated by Django 4.0.5 on 2022-06-08 18:18

import contest_arena.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=contest_arena.models.get_meme_image_upload_path)),
                ('sound', models.FileField(upload_to=contest_arena.models.get_meme_sound_upload_path)),
                ('text', models.TextField()),
                ('meme_for', models.IntegerField(default=-1, help_text='Alum = 0 & Student = 1')),
                ('meme_type', models.IntegerField(default=-1, help_text='Fail = 0 & Success = 1')),
            ],
        ),
    ]
