# Generated by Django 4.0.5 on 2022-06-09 06:11

import contest_arena.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest_arena', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('info', models.CharField(blank=True, max_length=300, null=True)),
                ('info_link', models.URLField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.FileField(null=True, upload_to=contest_arena.models.get_puzzle_upload_path)),
                ('ans', models.CharField(max_length=200)),
                ('visible', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Puzzle',
            },
        ),
    ]
