# Generated by Django 4.0.5 on 2022-06-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest_arena', '0002_puzzle'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='level',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
