# Generated by Django 4.0.5 on 2022-06-09 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_participant_acc_type'),
        ('contest_arena', '0003_puzzle_level_alter_puzzle_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuzzleForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans', models.TextField()),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.participant')),
                ('puzzle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contest_arena.puzzle')),
            ],
        ),
    ]
