# Generated by Django 4.0.5 on 2022-06-14 13:01

import contest_arena.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest_arena', '0004_puzzleform'),
    ]

    operations = [
        migrations.CreateModel(
            name='HackerManImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=contest_arena.models.get_hackerman_image_upload_path)),
                ('image_for', models.IntegerField(default=-1, help_text='Alum = 0 & Student = 1')),
            ],
        ),
    ]
