# Generated by Django 4.0.5 on 2022-06-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest_arena', '0006_alumnihackermanquotes_currentstudenthackerquotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='ans',
            field=models.CharField(max_length=50),
        ),
    ]
