# Generated by Django 4.0.5 on 2022-06-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest_arena', '0007_alter_puzzle_ans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='ans',
            field=models.CharField(max_length=20),
        ),
    ]
