# Generated by Django 4.0.5 on 2022-06-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest_arena', '0010_rename_currentstudenthackerquotes_alumnihackermanquote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackermanimage',
            name='image_for',
            field=models.IntegerField(default=-1, help_text='Alum = 1 & Student = 2'),
        ),
        migrations.AlterField(
            model_name='meme',
            name='meme_for',
            field=models.IntegerField(default=-1, help_text='Alum = 1 & Student = 2'),
        ),
    ]
