# Generated by Django 4.0.5 on 2022-06-29 12:36

import contest_arena.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest_arena', '0012_alter_hackermanimage_image_for_alter_meme_meme_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='sound',
            field=models.FileField(blank=True, default=None, null=True, upload_to=contest_arena.models.get_meme_sound_upload_path),
        ),
        migrations.AlterField(
            model_name='meme',
            name='text',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
