# Generated by Django 4.0.5 on 2022-07-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest_arena', '0013_alter_meme_sound_alter_meme_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackermanimage',
            name='test_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meme',
            name='test_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
