# Generated by Django 4.0.5 on 2022-06-23 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0006_remove_participant_batch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('time', models.DateTimeField()),
                ('status', models.IntegerField(default=0, help_text='Incorrect = 0 & Correct = 1')),
                ('ans', models.CharField(max_length=50)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.participant')),
            ],
        ),
    ]
