# Generated by Django 4.0.5 on 2022-06-23 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_participant_batch_and_more'),
        ('shomobay_shomiti_detector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.participant'),
        ),
    ]
