# Generated by Django 4.0.5 on 2022-06-23 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_participant_batch'),
        ('shomobay_shomiti_detector', '0002_alter_submission_participant'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectorGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=12, default=0, max_digits=30)),
                ('participant1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant1', to='user.participant')),
                ('participant2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant2', to='user.participant')),
            ],
        ),
    ]
