# Generated by Django 4.0.5 on 2022-06-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shomobay_shomiti_detector', '0003_detectorgraph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectorgraph',
            name='weight',
            field=models.FloatField(default=0.5),
        ),
    ]
