# Generated by Django 4.0.5 on 2022-06-08 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='participant',
            table='user_participant',
        ),
    ]
