# Generated by Django 4.0.5 on 2022-06-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_participant_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='acc_type',
            field=models.IntegerField(default=0, help_text='Alum = 1 & Student = 2'),
        ),
    ]
