# Generated by Django 4.0.5 on 2022-06-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_participant_acc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
