# Generated by Django 4.0.5 on 2022-06-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_participant_isactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='position',
        ),
        migrations.AddField(
            model_name='participant',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='student_ID',
            field=models.CharField(max_length=7),
        ),
    ]
