# Generated by Django 4.0.5 on 2022-06-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_participant_isactive_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='batch',
        ),
        migrations.AddField(
            model_name='participant',
            name='last_successful_submission_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='student_ID',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
