# Generated by Django 4.0.5 on 2022-06-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_participant_max_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='curr_level',
            field=models.IntegerField(default=1),
        ),
    ]
