# Generated by Django 4.0.5 on 2022-06-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_participant_curr_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='max_weight',
            field=models.FloatField(default=0.5),
        ),
    ]
