# Generated by Django 4.0.5 on 2022-06-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_participant_max_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='last_successful_submission_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
