# Generated by Django 4.0.5 on 2022-07-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_participant_last_successful_submission_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='max_weight',
            field=models.FloatField(default=0.2),
        ),
    ]
